### ISSUE TITLE
Unable to install collection via namespace and collection name

### ISSUE THREAD

**Issue by Ray-Gill** [redhat-cop/infra.convert2rhel#20]
The install steps here: https://github.com/oamg/infra.convert2rhel/blob/main/README.md?plain=1#L31
```bash
ansible-galaxy collection install infra.convert2rhel
```

Fails with:
```
ERROR! Failed to resolve the requested dependencies map. Could not satisfy the following requirements:
* infra.convert2rhel:* (direct request)
```

Expectation: is that the Galaxy collection install via namespace and collection name combination.

Looking at the `galaxy.yml` it does not appear to be correctly configured, e.g. https://github.com/oamg/infra.convert2rhel/blob/main/galaxy.yml#L18

Workaround, install via GitHub URL: `ansible-galaxy collection install -vvv git+https://github.com/oamg/infra.convert2rhel.git`

Note: Which some older version of Ansible Galaxy and Python seem not to support

**Comment by r0x0d** [comment]
Hi, @Ray-Gill! Thanks for your report! We are still working on publishing the collection to ansible galaxy, we just haven't got the time we liked to push this through. We have this work tracked internally, though, so I can assure you it won't fall into the void. 

I will be working with a couple of other colleagues of mine to make sure we can push the collection to galaxy as soon as possible. In the meantime, the best course of action we have right now is updating the README.md to include your workaround. 

Sorry for the inconvenience. As soon as we have it published, I will let you know by here.

**Comment by r0x0d** [comment]
Hi, @Ray-Gill! We just recently published the collection to galaxy: https://galaxy.ansible.com/ui/repo/published/infra/convert2rhel/

Would you mind trying it again?

**Comment by r0x0d** [comment]
Hi, @Ray-Gill! I'm closing this issue as it is published in ansible galaxy as well as a validated content under automation hub in Red Hat Console.
