### ISSUE TITLE
Add a link to Ansible Galaxy

### ISSUE THREAD

**Issue by bocekm** [redhat-cop/infra.convert2rhel#39]
Mention the availability of the collection in Ansible Galaxy in the README:
https://galaxy.ansible.com/ui/repo/published/infra/convert2rhel/

**Comment by r0x0d** [comment]
We can add a mention to that, but we have a whole paragraph for it already: https://github.com/redhat-cop/infra.convert2rhel?tab=readme-ov-file#installing-the-collection-from-ansible-galaxy 

It is a guide how to install/use it through ansible galaxy

**Comment by bocekm** [comment]
I think it'd be still worth it. E.g. Foreman links to it from their README https://github.com/theforeman/foreman-ansible-modules/?tab=readme-ov-file#installation-from-ansible-galaxy.

When were talking to solution architects today I wanted to send them a link to the Galaxy webpage. But all I had was a link to this github repo. It took me a while to find a link to Galaxy so I think it'd be handy to link to it from this repo for cases similar to the one I faced today.

**Comment by r0x0d** [comment]
It does make sense, indeed. Merged #40 that solves this.
